export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST";
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS";
export const ADD_PRODUCTS_FAILURE = "ADD_PRODUCTS_FAILURE";

export const PATCH_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST";
export const PATCH_PRODUCTS_SUCCESS = "PATCH_PRODUCTS_SUCCESS";
export const PATCH_PRODUCTS_FAILURE = "PATCH_PRODUCTS_FAILURE";

export const DELETE_PRODUCTS_REQUEST = "DELETE_PRODUCTS_REQUEST";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE";